### ISSUE TITLE
encode character talents

### ISSUE THREAD

**Issue by eikofee** [eikofee/eikonomiya-data#3]
I still need to think about the data structure.

Maybe use a structure similar to Buff Objects but specific for talents ?
Something like this:
```
talent name:
  text: (text from game to explain the talent)
  type: (static or levelable)
  effect:
    - name1: (name of the effect, such as "1-Hit DMG" in NA talents, etc...)
      type: basic, bool, stack, ...
      category: (element of dmg, heal, something like that. use 'other' for additionnal numbers not impacting damage computation ?)
      scaling: (stat used in computing the dmg, such as atk%, hp%, etc...)
      multiplier: (float, the % listed in game, can be an array to list every value for each level)
    - name2: ...
```
